### ISSUE TITLE
您好，请问在ubuntu上用什么编译器编译、运行

### ISSUE THREAD

**Issue by Armida220** [RemoteSensingFrank/LidarProc#1]

**Comment by RemoteSensingFrank** [comment]
cmake构建，gcc编译

**Comment by Armida220** [comment]
linux新手。感谢指导!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Frank Wu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月20日(星期三) 下午5:44
收件人:&nbsp;"RemoteSensingFrank/LidarProc"<LidarProc@noreply.github.com&gt;;
抄送:&nbsp;"292350357"<292350357@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [RemoteSensingFrank/LidarProc] 您好，请问在ubuntu上用什么编译器编译、运行 (#1)





 
cmake构建，gcc编译
